### ISSUE TITLE
Face Masks

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#105]
Do you have any suggestions on how to improve your project to work with face masks. With the crazy world we live in people are using face masks and im finding that i am not able to recognize people's faces.

Thank you.

**Comment by takuya-takeuchi** [comment]
@khinklenj 
I think it is hard to implement mask detection with current face detection network.
Because it is finished product.
So I guess it is not bad to check whether detected face is with mask or not by image classification.

**Comment by khinklenj** [comment]
My thought was is there a way to recognize a person even with a mask on or off

**Comment by takuya-takeuchi** [comment]
oh, sorry.

But face detection is important task before face recognition.
It is meaningless if system cannot detect masked face.

FaceRecognitionDotNet and face_recognition does not have ability to detect masked face.
And it is hard for these library to extract feature data from masked face.

Because

* non-masked area is small and it means that human face feature is very few
  * It may occur false positive or false negative.
* masked area has meaningful feature? I don't thinks so.

**Comment by khinklenj** [comment]
Thank you thats what I though but just wanted to verify
