### ISSUE TITLE
FaceLandmark not static

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/FaceRecognitionDotNet#30]
I'm using `FaceRecognition` thorugh the static method calls. My images are not on disk therefore using the `Create` method does not work for me.

Please make`FaceLandmark` method static.

cc @takuya-takeuchi

**Comment by takuya-takeuchi** [comment]
FaceLandmark requires face model data.
So if it makes static, we has to pass model file path when calling it. It is non-sence.

I guess you want to avoid to create Image instance because your images are not on strage.

You can use FaceRecognition.LoadImage method.
It loads image data from byte[]. If your image come from stream, you can create Image instance w/o saving as file.

**Comment by turowicz** [comment]
ok
