### ISSUE TITLE
Possibility to return  128-dimension points?

### ISSUE THREAD

**Issue by Hershef** [takuya-takeuchi/FaceRecognitionDotNet#65]
Is there a possibility to return 128-dimension points like in the original python examples? 
aka the face vectors to be saved on a database or so? 

`face_encodings = face_recognition.face_encodings(face_image)`

**Comment by takuya-takeuchi** [comment]
@Hershef 
Yes, FaceEncodings method returns array of FaceEncoding contains 1x128-dimension Matrix.

you can use Serialize method.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/1d99e43591f6996910ab1a2abc0facbdd1ee24f4/test/FaceRecognitionDotNet.Tests/FaceRecognitionTest.cs#L655

**Comment by ycdaskin** [comment]
hello @takuya-takeuchi, 
first, thank you for making this great wrapper.
second, i don't understand how serialization can be a solution to get 1d double array. as i understand from the question i think people (and me) need to get an array like this: [0.001212, -0.13213123 ...]. i need this because i want to save every single measurement into seperate columns on a database table.

**Comment by takuya-takeuchi** [comment]
@ycdaskin 
C# Serializer will output single binary data. So it could satisfy your requirement.

Do you want to reuse raw array encode data for other application, right?
If so, FRDN does not provide method to convert FaceEncoding to raw byte array.

**Comment by ycdaskin** [comment]
@takuya-takeuchi 
thank you for response. actually i am calculating the face distances on database side using euclidian distance method. that's why i need a 1x128 double array. getting this array would be nice. it seems i have to continue using python :(
thanks anyway.

**Comment by takuya-takeuchi** [comment]
It seems that the reporter can resolve issue.
