### ISSUE TITLE
Retrain helen dataset

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/FaceRecognitionDotNet#85]
from #84 

> Also I was wondering how often I have to retrain this dataset. Does it get updates or is it a one time train dataset.

**Comment by takuya-takeuchi** [comment]
I have questions.

* What does it mean 'retrain'?
* What does it mean 'updates'?

I guess you need to resume or train additinal image for existing model. Is it correct?
If so, answer is NO.
Because shape_predictor_trainer does not provide resume function unlike dnn trainer class.
It is limitation of dlib.

**Comment by SamuelvVelzen** [comment]
hi, yeah I mean in order to improve the model, the detection of faces and facial landmarks. It needs updates / retraining to improve. 

Despite the limitation of Dlib do we have to worry about an outdated Helen model. And if so should we look more to applications dat use machine learning to detect faces.
