### ISSUE TITLE
LoadImage with Span<Byte> or IntPtr

### ISSUE THREAD

**Issue by vpenades** [takuya-takeuchi/FaceRecognitionDotNet#88]
Currently, `LoadImage ` accepts a `Byte[]` as the source image.

Could it be possible to create images from other memory models? 

I am working with Memory<T>, Span<T>, and IntPtr.

I also believe that Memory<T> is a better option that Byte[] , because Byte[] can be automatically converted to Memory<T>, and can be pinned.

**Comment by takuya-takeuchi** [comment]
@vpenades 

Thank you for your suggestion!!
I have not yet used Spant<T>.
Is this able to convert to byte[] or IntPtr?
Because Image class hold Matrix<T> and it need to accept them in P/Invoke.
It looks like to be waste.

But I think IntPtr is good idea.
So it can implement to DlibDotNet and FaceRecognitionDotNet.

**Comment by vpenades** [comment]
If the underlaying DlibDotNet uses IntPtr, then  exposing IntPtr is fine.

**Comment by takuya-takeuchi** [comment]
@vpenades 
Sorry too late response.

> The objective is to avoid a memory copy, so, something like this would be very useful:

I guess dlib (native of DlibDotNet) needs to copy data from caller.
I created the above overload but it may be meaningless.
